### PR TITLE
added separate dialog to input task body

### PR DESCRIPTION
**Pull request by luutuankiet**
enhancing the base cli with an optional dialog to input task body.  
note this requires gxmessage util to work : `sudo apt install gxmessage`

### CODE REVIEW

**Comment by UnkwUsr** [comment]
Thank you for this pull request!

I would not like to add dependencies, so I tried to unify interface for getting description text and got 2 solutions:

1. Read description text from stdin: https://github.com/UnkwUsr/ticktask/commit/4213dda46e7ee3ea957b1cea77c412b3922a6905

2. Get description text by calling function specified in user config: https://github.com/UnkwUsr/ticktask/commit/a579d9f08abdc6e7f8ddc0ae6ac0187598166b8c

At first I was looking for solution number 1, as it looked "unix way" to me:D. But really, it's quite hard to use in real world, because we always need to write another wrapper script like:

```bash
#!/bin/bash
gxmessage --entry Type description | ticktask "$@"
```
UPD: it also have problem with gxmessage pops up before ticktask checks for "no arguments passed" (so you type long description and then ticktask says that you forgot to provide title)

So, now I think solution number 2 can be more useful. To use it, you need to only add this to your config:

```bash
cmd_get_description() {
    gxmessage --entry Type description
}
```

Can you test it please and give feedback?

**Comment by luutuankiet** [comment]
hey! i see that you've cleaned up the code nicely. I pondered about both of your ideas and prefer solution # 2 which is separating the task description input.

If we go with the no dependency route, how about the quick old `read` command? [cc85565](https://github.com/UnkwUsr/ticktask/pull/1/commits/cc85565b3bbab36e21efacdc94b0b0fb4b758015) this should do the trick without much hassle.

**Comment by UnkwUsr** [comment]
> how about the quick old read command

I've described problems with it in previous comment:

> But really, it's quite hard to use in real world, because we always need to write another wrapper script like:
> 
> ```bash
> #!/bin/bash
> gxmessage --entry Type description | ticktask "$@"
> ```
> 
> UPD: it also have problem with gxmessage pops up before ticktask checks for "no arguments passed" (so you type long description and then ticktask says that you forgot to provide title)

Or you've managed to solve them? Anyway, how do you usually run `ticktask` with your patch?

**Comment by luutuankiet** [comment]
might be due to different use case - for mine I use [albert](https://github.com/albertlauncher/albert) to launch a direct terminal command `> t task title`  (t is aliased to ticktask's, "task title" as passed parameter) then a terminal window opens and continue the script at `read` to ask for task description input. I also appended my ticktask with `kill -9 $PPID` to automatically close the terminal window once done.

**Comment by UnkwUsr** [comment]
Applied solution number 2. Check new [./config.example.sh](./config.example.sh) for ideas how to update your setup

**Pull request closed without merging**
